### PR TITLE
Style changes for LiveComs

### PR DESCRIPTION
**Pull request by liantze**
Two-column layout; blurb alongside abstract; checklists; algorithms; numbered section headings.

### CODE REVIEW

**Comment by davidlmobley** [comment]
Thanks, @liantze ! We're super glad to have these updates.

**Comment by jchodera** [comment]
This looks beautiful, @liantze!

**Comment by liantze** [comment]
Thank you @davidlmobley @jchodera , glad you like it so far! 😄

**Comment by mrshirts** [comment]
One question: when I compile it, I get the web address of the GitHub repository overflowing into the abstract.  It doesn't appear to do this in the version that LianTze posted.  See below:
[overflow_of_address.pdf](https://github.com/livecomsjournal/article_templates/files/1392891/overflow_of_address.pdf)

**Comment by liantze** [comment]
@mrshirts Hmm, were you compiling with pdflatex or latex+dvipdf? Or which MikTeX/TeX Live version are you on?

**Comment by mrshirts** [comment]
This was compiled with luatex ('luatex --version' gave This is LuaTeX, Version beta-0.80.0 (TeX Live 2015) (rev 5238)) since I couldn't compile with pdflatex (See https://github.com/livecomsjournal/article_templates/issues/26 for discussion of that).

**Pull request merged**
