### PR TITLE
Update to BST file to create https links from the DOI key.

### PR DESCRIPTION
**Pull request by dwsideriusNIST**
Modified DOI handler in BST file to create proper https links. NOTE: this does not affect the URL tag, which may be necessary for articles that do not have assigned DOIs.

See https://github.com/dmzuckerman/Sampling-Uncertainty/blob/master/main.pdf for result.

### CODE REVIEW

**Comment by davidlmobley** [comment]
Thanks! You're also making an update to the documentation to note this as well, @dwsideriusNIST ? Specifically, I'd imagine we'd want:
- Something in this repo (perhaps in our example template?) which notes this; perhaps also in a README here?
- Maybe something on our livecomsjournal.github.io page as well? 

Otherwise looks good to merge.

**Comment by davidlmobley** [comment]
(LMK if you want me to merge or if you want to get any of that in at the same time.)

**Comment by dwsideriusNIST** [comment]
@davidlmobley I'm planning to get to this, just didn't have time this week. My intention is exactly as you suggested:
- add a "guidelines for the bibliography" .md file to the article_templates repo
- comments somewhere in the livecomsjournal.github.io
- lastly, update the example .BIB file including some in-file comments

**Comment by dwsideriusNIST** [comment]
@davidlmobley I've amended the PR to include a markdown file and updated sample bibliography.

**Comment by dwsideriusNIST** [comment]
@davidlmobley Sorry, I've let this PR sit too long. To reiterate the situation:
1. This PR is ready "as is"
2. I have put in a PR (#139) for the livecomsjournal.github.io repo that expands on the bibliography guidelines, referencing the new bibliography_guidelines.md file in this (article_templates) repo.

**Comment by davidlmobley** [comment]
Sorry, @dwsideriusNIST , I missed this. Merging.

**Pull request merged**
