### PR TITLE
Add templates for other article types

### LINKED ISSUE #20: Make changes to templates
This is a to-do list spinning off of discussion in #16 ; it will be updated as we get more discussion there. Currently, I'm expecting we'll want to make at least these changes to the template:

**Important:**
- [x] Setup checklists (perhaps a custom checklist environment) providing [visually appealing checklist-like panels](https://github.com/livecomsjournal/article_templates/issues/16#issuecomment-327872610)
- [x] Date, ~DOI and version~ in the left column of the first page (see #10 )
- [x] Add an official location for a link to the GitHub repo (below corresponding authors) have [a note steering reader comments/feedback to GitHub repo](https://github.com/livecomsjournal/article_templates/issues/16#issuecomment-330896332); also do the same in a subsection at the end just before author contributions, to emphasize the importance of this.
- [x] [Broaden conflicts section](https://github.com/livecomsjournal/article_templates/issues/16#issuecomment-330665758) to indicate how conflicts can be other than financial.
- [x] [Get rid of gutter after first page](https://github.com/livecomsjournal/article_templates/issues/16#issuecomment-331018737), [probably going to two column for subsequent pages](https://github.com/livecomsjournal/article_templates/issues/16#issuecomment-331718195)
- [x] Provide a way to easily display nicely formatted fixed-width code blocks for programming code/pseudocode, rather like what GitHub provides as discussed [here](https://github.com/livecomsjournal/livecomsjournal.github.io/issues/29#issuecomment-332718686), kind of like:
```python
x = 23
y = 37
for i in range(23): print x*y
```

**Probably nice to have:**
- [x] Sans serif math fonts to go with the sans serif text

**Very minor**
- [x] [p6 of our sample PDF has differing spacing between the lines](https://github.com/livecomsjournal/article_templates/blob/master/templates/livecoms-template-bestpractices.pdf) which seems odd and should probably be fixed.

**And in a final stage:**
- [x] After all of the above are done, create templates for the other article types (as in #9 ) 
- [x] Make custom changes for specific types of documents -- perhaps Best Practices documents should use [more of the full width of the page](https://github.com/livecomsjournal/article_templates/issues/16#issue-255951019) for body text and checklists
- [x] Organize each template as appropriate for the type of document; e.g. best practices documents may need to explicitly note scope, etc., as [noted here](https://github.com/livecomsjournal/article_templates/issues/16#issue-255951019).

### PR DESCRIPTION
**Pull request by davidlmobley**
This resolves #20 by:
- Moving the current best practices "template" to a "sample" file instead, so that the templates can be more minimal (e.g. not have sample images, etc., that our users will have to strip out)
- Creating a new best practices template which conforms to our guidance for that type of document (e.g. explicitly giving the scope, giving a checklist, giving a rationale, etc.)
- Creating templates for the other types of documents which conform to our current document-specific guidance
- Adding README file in templates directory explaining what's there

### CODE REVIEW

**Comment by mrshirts** [comment]
I'm seeing a problem with the main template that we do need to resolve at some point: 
bad_repo
The repository name leaks into the abstract.  Not sure how to change.

**Comment by davidlmobley** [comment]
That's odd. Is this in the repo or on yours?i was fairly sure this was resolved already.



David Mobley 949-385-2436 (cell)
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.8.132&pv=5.1&source=email_footer_2] On Sat, Nov 25, 2017 at 6:39am, Michael Shirts < notifications@github.com [notifications@github.com] > wrote:
I'm seeing a problem with the main template that we do need to resolve at some point:
[https://user-images.githubusercontent.com/4274132/33231520-bbc79cda-d1b3-11e7-875c-212662074ab4.png]
The repository name leaks into the abstract. Not sure how to change.

**Comment by davidlmobley** [comment]
The below is what I see on mine, @mrshirts , and in the PDFs in this PR. It looks correct. I take it you're seeing something different when you compile locally?

I'm using MacTex from recently in 2017.

template

**Comment by mrshirts** [comment]
I get this problem when I pull down that PR locally, and I compile with lualatex, since I haven't updated my TexShop version yet past 2015. So maybe a lualatax problem?  I will download a new version when I get home.

**Comment by davidlmobley** [comment]
> This is fine, though it means that if we want to change anything, we will have to edit 5 of them to change that thing

Agreed, yes, but we can't provide useful templates that give some guidance on structure without doing this, I don't think. Also, MOST things I can think we might change are things which are in the class rather than in the individual templates.

**Pull request merged**
